package com.example.rickandmortyapp.utils

const val CALLBACK_ERROR_ALL_CHARACTERS = "ERROR_CALL_ALL_CHARACTER"
const val ERROR_VIEW_MODEL_CALL_ALLCHARACTERS = "ERROR_CALL_ALL_CHARACTERS_VIEW_MODEL"
const val CALLBACK_ERROR_INFO_ABOUT_PAGE = "ERROR_CALLBACK_PAGE"
const val CALL_BACK_ERROR_GET_CHARACTER_PER_PAGE = "ERROR_CALLBACK_CHARACTERS_PER_PAGE"
const val CALLBACK_SUCESS_GET_CHARACTER_PER_PAGE = "SUCESS_CALLBACK_CHARACTERS_PER_PAGE"